### ISSUE TITLE
Support for Bitbucket Server user's "Access Token"

### ISSUE THREAD

**Issue by ymartin59** [mendhak/teamcity-stash#33]
Hello
Would it be possible to allow "access token" as alternate credential instead of password for REST authentication ?
Thank you in advance. Regards

**Comment by mendhak** [comment]
Interesting q. It does look possible - https://confluence.atlassian.com/bitbucketserver/personal-access-tokens-939515499.html - just need to send the token as part of the `Authorization: Bearer` header

    curl -H "Authorization: Bearer MDM0MjM5NDc2MDxxxxxxxxxxxxxxxxxxxxx" 
    http://localhost:7990/bitbucket/rest/api/1.0/projects/WORK/repos/my-repo/commits/?until=master

instead of the `Authorization: Basic` that's currently sent.  

One way to deal with this - in the UI if the user leaves the username blank, then treat it as a bearer token.  Probably needs changing to the UI to say "Username or Personal Access Token" and make the password field optional.  

Then if only a username has been passed in, setting that as the header.  

https://github.com/mendhak/teamcity-stash/blob/master/server/src/main/java/mendhak/teamcity/stash/api/StashClient.java#L138


But you can see the code has been untouched in years.  I am wondering - does the [Jetbrains plugin](https://confluence.jetbrains.com/display/TCD10/Commit+Status+Publisher) already work with token?

**Comment by ymartin59** [comment]
In fact a collegue of mine was the effective requester and surprisingly, submitting both username and token (as password) is working properly

**Comment by mendhak** [comment]
Just to confirm it, I've noticed that on SAML enabled instances, the only way for devs to use git over https is by entering their token in the password field (or just use SSH keys)
